# These are supported funding model platforms

github: [ccrama, timawesomeness] #If any contributor wants to add themselves here, please let me know!
custom: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=56FKCCYLX7L72
